In [1]:
import numpy as np

In [2]:
np.arange(2, 50, 3).tolist()


[2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47]

Question 2:

In [6]:
import numpy as np
list1=[]
list2=[]
print('enter first list elements:')
for i in range(0,5):
    ele=int(input())
    list1.append(ele)
print('enter second list elements:')
for i in range(0,5):
    ele1=int(input())
    list2.append(ele1)
arr1=np.array(list1)
arr2=np.array(list2)
print(arr1)
print(" ")
print(arr2)
arr3=np.concatenate((arr1, arr2), axis=None)
print(arr3)
print('Sorted concatenated array:')
print(np.sort(arr3))

enter first list elements:
10
9
8
7
6
enter second list elements:
5
4
3
2
1
[10  9  8  7  6]
 
[5 4 3 2 1]
[10  9  8  7  6  5  4  3  2  1]
Sorted concatenated array:
[ 1  2  3  4  5  6  7  8  9 10]


Question 3:

In [8]:
import numpy as np

# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )

# Printing shape of array
print("Shape of array: ", arr.shape)

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

Shape of array:  (2, 3)
Size of array:  6


Question 4:

In [9]:
a_1d_array = np.array([1, 2, 3, 4])
print(a_1d_array)

reshaped_to_2d = np.reshape(a_1d_array, (-1, 2))
print(reshaped_to_2d)

[1 2 3 4]
[[1 2]
 [3 4]]


Question 5:

In [10]:
a1 = np.arange(1, 10)
print(a1)
a2 = np.arange(11, 20)
print(a2)
stack0 = np.stack((a1, a1, a2, a2))
print(stack0)
stack_long = np.hstack((a1, a2))
#stack horizontally
print(stack_long)

#stack vertically
stack_col = np.vstack((a1, a2))
print(stack_col)

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[[ 1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19]]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3  4  5  6  7  8  9]
 [11 12 13 14 15 16 17 18 19]]


Question 6:

In [13]:
number_list = np.array([1, 1, 2, 3, 4, 4, 1])

(unique, counts) = np.unique(number_list, return_counts=True)
frequencies = np.asarray((unique, counts)).T
print(frequencies)

[[1 3]
 [2 1]
 [3 1]
 [4 2]]
